name: 'OpenAI Moderation'
description: 'Moderate user content'
inputs:
  openai-api-key:
    description: 'OpenAPI API Key to use for this plugin'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
